version: '3'
services:

  db:
    build: 
      context: .
    restart: always
    volumes:
      - postgres-ssl-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
      - 5434:8000
    environment:
      TZ: "Asia/Kolkata"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-root}"
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  postgres-ssl-data: