version: '3'
services:

  db:
    build: 
      context: .
    restart: always
    volumes:
      - postgres-ssl-data:/var/lib/postgresql/data
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    ports:
      - 5433:5432
    environment:
      TZ: "Asia/Kolkata"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-root}"
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  postgres-ssl-data: